parameters:
  env: ""
  environment: ""
  enableProvisioning: ""

stages:
# Stage: Deploy Function
- stage:
  displayName: "${{parameters.environment}} - Deploy"

  variables:
    env: "${{parameters.env}}" # The replacetokens task is working with variables not parameters.
    dropPath: "$(Pipeline.Workspace)/drop"
    resourceGroup: "test-ResGroup"
    functionAppName: "DevOpsTestFunc${{variables.env}}"

  jobs:
  - deployment: ProvisionAzureResources
    displayName: "Provision Azure Resources"
    
    condition: "${{parameters.enableProvisioning}}"
    
    environment: "${{parameters.environment}}"

    pool:
      vmImage: "$(vmImageName)"
      
    variables: # Has to be used in this format due to the group.
    - name: "armDir"
      value: "$(dropPath)/provisioning"
    - group: "FuncApp-VG"
    # The following values from variable group + KeyVault and replace token use it.
    - name: "MyCustomValue"
      value: $(FuncApp-MyCustomValue)
    - name: "MyConnectionString"
      value: $(FuncApp-MyConnectionString)

    strategy:
      runOnce:
        deploy:
          steps:
          # Install the Replace Tokens from the marketplace
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: "Replace variables in ARM templates"
            inputs:
              rootDirectory: "$(armDir)"
              targetFiles: "*-parameters.json"
              verbosity: "detailed"
              # encoding: "utf-8"

          - task: AzureResourceGroupDeployment@2
            displayName: "Provisioning: AppInsights"
            inputs:
              azureSubscription: "$(subscriptionName)"
              resourceGroupName: "${{variables.resourceGroup}}"
              deploymentName: "AppInsights${{variables.env}}"
              csmFile: "$(armDir)/AppInsights-template.json"
              csmParametersFile: "$(armDir)/AppInsights-parameters.json"

          #- task: AzurePowerShell@4
          #  displayName: "Provisioning: AppInsights"
          #  inputs:
          #    azureSubscription: "$(subscriptionName)"
          #    scriptPath: "$(armDir)/ResourceGroupDeployment.ps1"
          #    scriptArguments: "-deploymentName 'AppInsights${{variables.env}}' -resourceGroup '${{variables.resourceGroup}}' -templateFile '$(armDir)/AppInsights-template.json' -templateParameterFile '$(armDir)/AppInsights-parameters.json'"
          #    azurePowerShellVersion: "latestVersion"

          - task: AzureResourceGroupDeployment@2
            displayName: "Provisioning: StorageAccount"
            inputs:
              azureSubscription: "$(subscriptionName)"
              resourceGroupName: "${{variables.resourceGroup}}"
              deploymentName: "DevOpsTestStorage${{variables.env}}"
              csmFile: "$(armDir)/StorageAccount-template.json"
              csmParametersFile: "$(armDir)/StorageAccount-parameters.json"

          - task: AzureResourceGroupDeployment@2
            displayName: "Provisioning: FunctionApp"
            inputs:
              azureSubscription: "$(subscriptionName)"
              resourceGroupName: "${{variables.resourceGroup}}"
              deploymentName: "$(functionAppName)"
              csmFile: "$(armDir)/FunctionAppOsWindows-template.json"
              csmParametersFile: "$(armDir)/FunctionApp-parameters.json"

  - deployment: DeployAzureFunction
    displayName: "Deploy Azure Function"
    
    dependsOn: "ProvisionAzureResources"
    condition: or(succeeded(), not(${{parameters.enableProvisioning}}))

    environment: "${{parameters.environment}}"

    pool:
      vmImage: "$(vmImageName)"

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: "Deploy Azure Function App"
            inputs:
              azureSubscription: "$(subscriptionName)"
              appType: "functionApp" # To deploy Function on Linux: "functionAppLinux"
              appName: "$(functionAppName)"
              deploymentMethod: "zipDeploy"
              package: "$(dropPath)/FunctionAppProject/FunctionAppProject.zip"